Repository CA-G12/API-shatha-nader-abdallah, pull requests merged in 2022-08, with the labels that each got.

#3 1 file structure
  JS/dom.js
  JS/logic.js
  JS/test.js
  index.html
  style.css
Labels: approved

#4 fetch function
  JS/logic.js
  index.html
Labels: approved

#10 update img
  IMG/fantasy.jpg
  IMG/shades.jpg
  IMG/video-player.png
Labels: done

#11 create header
  index.html
  style.css
Labels: awaiting-review

#13 7 create movies section
  JS/dom.js
  index.html
  style.css
Labels: awaiting-review

#14 Create music section
  JS/dom.js
  JS/fetch.js
  JS/test.js
  index.html
  style.css
Labels: approved

#15 make header responsive
  .vscode/settings.json
  index.html
  style.css
Labels: done

#17 Add target _blank to Link href #16
  JS/dom.js
Labels: merged

#18 created pop up with its functionality
  JS/dom.js
  index.html
  style.css
Labels: approved

#21 add header for movies section relates #20
  index.html
Labels: awaiting-review

#23 changed links
  JS/dom.js
Labels: awaiting-review

#25 write readme file relates #19
  README.md
Labels: awaiting-review

#26 animations and responsiveness of pop up
  JS/dom.js
  index.html
  style.css
Labels: approved

#29 add layout image for website relates #28
  README.md
Labels: approved

#30 made scroll and more
  style.css
Labels: approved
